---
title: V1 版本内存布局
---

packet-beta

0-3: 'Magic "HUFF"'
4: 'VER'
5: 'GFLG'
6-7: 'RES'
8-11: 'Magic "ENTR"'
12: 'EFLG'
13: 'PAD'
14-15: 'METL'
16-23: 'Original Size'
24-27: 'Tree Size'
28-31: 'Body Size'
32-47: 'Entry Metadata'
48-63: 'Tree Data'
64-95: 'Compressed Body'
96-127: '... Other Entries'
128-131: 'Magic "TAIL"'
132-139: 'Index Offset'
140-143: 'Global Checksum'